spring:
  application:
    name: copalpite
  datasource:
    url: jdbc:mysql://localhost:3306/copalpite?useSSL=false&serverTimezone=UTC
    username: root
    password: homenaranha90
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true